name: PHP CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  check-php:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check PHP Syntax
        run: |
          find . -name "*.php" -exec php -l {} \;