name: PHP CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  check-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check PHP Syntax
        shell: bash
        run: |
          set -e
          find . -name "*.php" -type f -print0 | while IFS= read -r -d '' file; do
            php -l "$file"
          done